spring:
  config:
    import: 
      - optional:file:../.env[.properties]
  application:
    name: ceasa-digital-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false

security:
  client-id: ${OAUTH2_CLIENT_ID:myclientid}
  client-secret: ${OAUTH2_CLIENT_SECRET:myclientsecret}

  jwt:
    duration: ${OAUTH2_JWT_DURATION:3600}
    refresh-duration: ${OAUTH2_REFRESH_DURATION:7200}
  
  oauth2:
    issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8080}
    jwk-set-uri: ${OAUTH2_JWK_SET_URI:http://localhost:8080/oauth2/jwks}

cors:
  origins: ${OAUTH2_CORS_ORIGINS:http://localhost:3000,http://localhost:5173}



spring.mail.host: smtp.gmail.com
spring.mail.port: 456
spring.mail.username: ${EMAIL_USERNAME} # VARIÁVEL DE AMBIENTE
spring.mail.password: ${EMAIL_PASSWORD} # VARIÁVEL DE AMBIENTE
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false      
      mail.smtp.ssl.enable: true            
      mail.smtps.ssl.checkserveridentity: true
      mail.smtps.ssl.trust: smtp.gmail.com
      mail.smtps.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtps.socketFactory.port: 465